# Generated by Django 2.0 on 2017-12-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Knockout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('games', models.ForeignKey(on_delete='cascade', related_name='event', to='players.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Olympics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2017, unique=True)),
                ('knockouts', models.ForeignKey(on_delete='cascade', related_name='olympics', to='players.Knockout')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('totalPoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('players', models.ForeignKey(on_delete='cascade', related_name='event', to='players.Players')),
            ],
        ),
        migrations.AddField(
            model_name='olympics',
            name='players',
            field=models.ForeignKey(on_delete='cascade', to='players.Players'),
        ),
        migrations.AddField(
            model_name='olympics',
            name='tourneys',
            field=models.ForeignKey(on_delete='cascade', related_name='olympics', to='players.Tourney'),
        ),
        migrations.AddField(
            model_name='knockout',
            name='players',
            field=models.ForeignKey(on_delete='cascade', to='players.Players'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete='cascade', related_name='player1', to='players.Players'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete='cascade', related_name='player2', to='players.Players'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete='cascade', related_name='game', to='players.Players'),
        ),
    ]
