# Generated by Django 2.0 on 2017-12-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
