# Generated by Django 2.0 on 2017-12-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_players_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knockout',
            name='games',
        ),
        migrations.RemoveField(
            model_name='knockout',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.RemoveField(
            model_name='olympics',
            name='knockouts',
        ),
        migrations.RemoveField(
            model_name='olympics',
            name='players',
        ),
        migrations.RemoveField(
            model_name='olympics',
            name='tourneys',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='tourney',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='tourney', to='players.Tourney'),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='name',
            field=models.CharField(default='bowling', max_length=50),
        ),
        migrations.DeleteModel(
            name='Knockout',
        ),
    ]
