# Generated by Django 2.0 on 2017-12-16 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0004_olympics_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympics',
            name='totalPlayers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourney',
            name='olympics',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='olympics', to='players.Olympics'),
        ),
    ]
