# Generated by Django 2.0 on 2017-12-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20171216_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='points',
            new_name='eventPoints',
        ),
    ]
