# Generated by Django 2.0 on 2017-12-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_olympics_isrunning'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='junk',
            field=models.CharField(default='junk', max_length=50),
            preserve_default=False,
        ),
    ]
