# Generated by Django 2.0 on 2017-12-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_players_junk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete='cascade', related_name='player', to='players.Players')),
                ('tourney', models.ForeignKey(null=True, on_delete='cascade', related_name='olympic', to='players.Tourney')),
            ],
        ),
    ]
