# Generated by Django 2.0 on 2017-12-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='player', to='players.Players'),
        ),
    ]
