# Generated by Django 2.0 on 2017-12-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20171219_0236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('player', 'tourney')},
        ),
    ]
