# Generated by Django 2.0.1 on 2018-01-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20180111_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='junk',
        ),
    ]
