# Generated by Django 2.0.1 on 2018-01-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_remove_players_junk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('olympics', models.ForeignKey(null=True, on_delete='cascade', related_name='olympicss', to='players.Olympics')),
                ('player', models.ForeignKey(null=True, on_delete='cascade', related_name='playerrs', to='players.Players')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='points',
            unique_together={('player', 'olympics')},
        ),
    ]
