# Generated by Django 2.0.1 on 2018-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_tourney_isranked'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='eventRound',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tourney',
            name='currentRound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league',
            name='event',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='ev', to='players.Tourney'),
        ),
        migrations.AddField(
            model_name='league',
            name='player1',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='p1', to='players.Players'),
        ),
        migrations.AddField(
            model_name='league',
            name='player2',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='p2', to='players.Players'),
        ),
        migrations.AddField(
            model_name='league',
            name='player3',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='p3', to='players.Players'),
        ),
        migrations.AddField(
            model_name='league',
            name='player4',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='p4', to='players.Players'),
        ),
    ]
