# Generated by Django 2.0.1 on 2018-01-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_auto_20180113_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='player2', to='players.Players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tourney',
            field=models.ForeignKey(on_delete='cascade', related_name='tourney', to='players.Tourney'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='game', to='players.Players'),
        ),
    ]
