# Generated by Django 2.0.1 on 2018-01-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_tourney_iscomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourney',
            name='isComplete',
        ),
        migrations.AddField(
            model_name='tourney',
            name='isRunning',
            field=models.BooleanField(default=True),
        ),
    ]
