# Generated by Django 2.0.1 on 2018-01-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_auto_20180114_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='winner',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='touneywinner', to='players.Players'),
        ),
    ]
