# Generated by Django 2.0.1 on 2018-01-19 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_tourney_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cascade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='players.Players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='players.Players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tourney',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourney', to='players.Tourney'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='players.Players'),
        ),
        migrations.AlterField(
            model_name='points',
            name='olympics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olympicss', to='players.Olympics'),
        ),
        migrations.AlterField(
            model_name='points',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerrs', to='players.Players'),
        ),
        migrations.AlterField(
            model_name='result',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerr', to='players.Players'),
        ),
        migrations.AlterField(
            model_name='result',
            name='tourney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olympic1', to='players.Tourney'),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='players.Players'),
        ),
        migrations.AlterField(
            model_name='score',
            name='tourney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olympic', to='players.Tourney'),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='olympics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olympics', to='players.Olympics'),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touneywinner', to='players.Players'),
        ),
    ]
